name: Docker main

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      Greeting: Hello
      SPRING_DATASOURCE_URL: jdbc:mysql://${{ secrets.DATASOURCE_URL }}/ci
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
        
      - name: Build the Docker image at ${{github.GITHUB_REPOSITORY }}
        run: docker build . --file Dockerfile --build-arg SPRING_DATASOURCE_USERNAME=${{env.SPRING_DATASOURCE_USERNAME}} --build-arg SPRING_DATASOURCE_USERNAME=${{env.DATASOURCE_USERNAME}} --build-arg SPRING_DATASOURCE_PASSWORD=${{env.DATASOURCE_PASSWORD}} --tag registry.jlosch.de/kemary.de/warehouse:latest
        
      - name: Build the Docker image at ${{github.GITHUB_REPOSITORY }}
        run: docker build . --file Dockerfile --build-arg SPRING_DATASOURCE_USERNAME=${{env.SPRING_DATASOURCE_USERNAME}} --build-arg SPRING_DATASOURCE_USERNAME=${{env.DATASOURCE_USERNAME}} --build-arg SPRING_DATASOURCE_PASSWORD=${{env.DATASOURCE_PASSWORD}} --tag registry.jlosch.de/kemary.de/warehouse:${GITHUB_REF_NAME}

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: https://registry.jlosch.de
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          name: registry.jlosch.de/kemary.de/warehouse:latest
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: https://registry.jlosch.de
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          name: registry.jlosch.de/kemary.de/warehouse:${GITHUB_REF_NAME}
